name: my-github-workflow
on: push
jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build --use-container
      - name: Test
        uses: github/codeql-action/analyze@v3
      - name: Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --region us-east-1
      - name: Release
        uses: actions/create-release@v1
