name: my-github-workflow
on: push
jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build
        run: sam build --use-container
      - name: Configure CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Test
        uses: github/codeql-action/analyze@v3
      - name: Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --region us-east-1
      - name: Determine Release Version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: Show Endpoint
        run: sam list endpoints --output json
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
